baseURL = 'https://aintbe.github.io/'
languageCode = 'en-us'
title = 'Logger'

[module]
  [[module.imports]]
  path = "github.com/nanxiaobei/hugo-paper"

[params]
  color = 'gray' # linen, wheat, gray, light

  # header social icons
  github = 'aintbe'
  instagram = 'cosmicbroom'

  # home page profile
  avatar = 'aint.imsorry@gmail.com' # gravatar email or image url
  name = '소리림'
  bio = '지구에 살고 있어요'
  
  # commento settings
  commento = 'https://comments.koreacentral.cloudapp.azure.com'

[taxonomies]
  tag = 'tag'
  category = 'category'

[menu]
  [[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'

  [[menu.main]]
  identifier = 'journal'
  name = '일기장'
  url = '/journal/'

[markup]
  [markup.highlight]
  style = 'onedark'

